version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:3000'
    # environment:
    # - MONGO_URI=mongodb://mongo:27017
    # - REDIS_HOST=localhost
    # - REDIS_PORT=6379
    # depends_on:
    #   # - mongo
    #   - redis

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo-data:/data/db

  # redis:
  #   image: redis:6.0.7
  #   ports:
  #     - '6379:6379'
# volumes:
#   mongo-data:
