version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:3000'
    environment:
      - MONGO_URI=mongodb://mongo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=secret
      - TMDB_API_KEY=f6fb5899bd0ef8f974fcedbdfb319014
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.0.7
    container_name: redis
    ports:
      - '6379:6379'
volumes:
  mongo-data:
